name: doc_editor_custom
description: Document Viewer and Editor with Custom TTF Fonts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  path_provider: ^2.1.0
  permission_handler: ^11.0.1
  syncfusion_flutter_pdfviewer: ^23.2.7
  flutter_quill: ^9.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets folder kuch nahi daalna, hum dynamically font load karenge
